choco pin add -n discord
choco pin add -n docker-desktop
choco pin add -n drawio
choco pin add -n epicgameslauncher
choco pin add -n Firefox
choco pin add -n geforce-experience
choco pin add -n goggalaxy
choco pin add -n GoogleChrome
choco pin add -n notepadplusplus
choco pin add -n notepadplusplus.install
choco pin add -n nvidia-display-driver
choco pin add -n origin
choco pin add -n postman
choco pin add -n steam
choco pin add -n steam-client
choco pin add -n ubisoft-connect
choco pin add -n vscode
choco pin add -n vscode.install